# Create base system
FROM scratch
MAINTAINER Igor Zalatov <flyrouter@gmail.com>
ADD debian_jessie_rootfs.tar.xz /

# Disable interactive
ENV DEBIAN_FRONTEND noninteractive

# Set timezone
RUN echo "Europe/Simferopol" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

# Resolve problem with execution policy-rc.d
RUN echo "exit 0" > /usr/sbin/policy-rc.d && chmod +x /usr/sbin/policy-rc.d

# Update and upgrade
RUN apt-get -qq -y -u update && apt-get -qq -y -u upgrade

# Install packages
RUN apt-get -qq -y --no-install-recommends install  apt-utils runit
RUN apt-get -qq -y --no-install-recommends install  dropbear sudo mc
RUN apt-get -qq -y --no-install-recommends install  wget iperf netcat

RUN apt-get -qq -y --no-install-recommends install  default-jre-headless jsvc
RUN wget http://www.ubnt.com/downloads/aircontrol/aircontrol_1.4.2-beta_all.deb &&\
         dpkg -i aircontrol_1.4.2-beta_all.deb &&\
         rm aircontrol_1.4.2-beta_all.deb

RUN sed -i -e's/JAVA_HOME=/#JAVA_HOME=/' /etc/init.d/aircontrol
RUN sed -i -e's/export\ JAVA_HOME/#export JAVA_HOME/' /etc/init.d/aircontrol
RUN mkdir -p /usr/share/aircontrol/logs/ && touch /usr/share/aircontrol/logs/server.log

# Expose the AirControl port
EXPOSE 9080

# Now make sure that runit will launch AirControl, via runit.
RUN mkdir -p /etc/service/aircontrol /var/run/aircontrol
RUN /bin/echo -e '#!/bin/sh' > /etc/service/aircontrol/run
RUN /bin/echo -e 'exec 2>&1' >> /etc/service/aircontrol/run
RUN /bin/echo -e 'exec sleep 300' >> /etc/service/aircontrol/run

# Make sure our run-script is executable.
RUN chown root.root /etc/service/*/run && chmod 755 /etc/service/*/run

# Setup a simple & stupid root password
RUN echo "root:airmax2016" | chpasswd

# Clean system
RUN apt-get -qq -y clean
RUN rm -rf usr/{{lib,share}/locale} usr/share/{man,doc,info}

# Launch runit
ENTRYPOINT ["/usr/sbin/runsvdir-start"]
